use std::collections::BTreeMap;
use std::collections::BTreeSet;
use std::path::PathBuf;

use pretty_assertions::assert_eq;

use tachi_core::infographic::compute_metadata;
use tachi_core::infographic::compute_most_exposed_layer;
use tachi_core::infographic::extract_prompt_scaffold;
use tachi_core::infographic::validate_infographic;
use tachi_core::infographic::ComponentRiskWeight;
use tachi_core::infographic::HeatMapRow;
use tachi_core::infographic::InfographicMetadata;
use tachi_core::infographic::InfographicValidationData;
use tachi_core::infographic::MaestroLayerDistributionEntry;
use tachi_core::infographic::SeverityDistributionEntry;
use tachi_core::infographic::TopFinding;
use tachi_core::parsers::{ScopeComponent, SeverityCounts};

#[test]
fn extract_prompt_scaffold_reads_the_risk_funnel_prompt_block() {
    let repo_root = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("..")
        .join("..");

    let scaffold = extract_prompt_scaffold("risk-funnel", Some(&repo_root));

    assert!(scaffold.found);
    assert!(scaffold
        .preamble
        .contains("DATA CONTENT (render this as visible text):"));
    assert!(scaffold.preamble.contains("STYLING DIRECTIVES"));
    assert!(scaffold.postamble.contains("FOOTER"));
    assert!(scaffold
        .postamble
        .contains("Generated by Tachi Threat Modeling Framework"));
    assert!(!scaffold.preamble.is_empty());
    assert!(!scaffold.postamble.is_empty());
}

#[test]
fn extract_prompt_scaffold_returns_empty_when_template_is_unknown() {
    let repo_root = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("..")
        .join("..");

    let scaffold = extract_prompt_scaffold("not-a-template", Some(&repo_root));

    assert_eq!(scaffold.found, false);
    assert_eq!(scaffold.preamble, "");
    assert_eq!(scaffold.postamble, "");
}

#[test]
fn compute_metadata_builds_expected_infographic_fields() {
    let threats_content = r#"
# Threat Model

### 3.1 Example Agent

### 4.2 Example Agent
"#;
    let frontmatter = BTreeMap::from([
        (String::from("date"), String::from("2026-06-05")),
        (String::from("schema_version"), String::from("1.4")),
    ]);
    let severity = SeverityCounts {
        critical: 2,
        high: 3,
        medium: 4,
        low: 5,
        note: 6,
        total: 20,
    };
    let scope_components = vec![
        ScopeComponent {
            name: String::from("API"),
            kind: String::from("Process"),
            description: String::from(""),
        },
        ScopeComponent {
            name: String::from("DB"),
            kind: String::from("Data Store"),
            description: String::from(""),
        },
    ];

    let metadata = compute_metadata(
        threats_content,
        &frontmatter,
        1,
        &severity,
        &scope_components,
        "Acme Project",
    );

    assert_eq!(metadata.project_name, "Acme Project");
    assert_eq!(metadata.scan_date, "2026-06-05");
    assert_eq!(metadata.tier, 1);
    assert_eq!(metadata.data_source_type, "compensating-controls");
    assert_eq!(metadata.total_findings, 20);
    assert_eq!(metadata.note_count, 6);
    assert_eq!(metadata.agent_count, 2);
    assert_eq!(
        metadata.risk_posture,
        "Residual risk — 2 Critical and 3 High findings across 2 components"
    );
    assert_eq!(metadata.schema_version, "1.4");
}

#[test]
fn validate_infographic_accepts_consistent_data() {
    let data = InfographicValidationData {
        metadata: InfographicMetadata {
            total_findings: 5,
            note_count: 1,
            ..Default::default()
        },
        severity_distribution: vec![
            SeverityDistributionEntry {
                label: String::from("Critical"),
                count: 1,
            },
            SeverityDistributionEntry {
                label: String::from("High"),
                count: 1,
            },
            SeverityDistributionEntry {
                label: String::from("Medium"),
                count: 1,
            },
            SeverityDistributionEntry {
                label: String::from("Low"),
                count: 1,
            },
        ],
        heat_map: vec![HeatMapRow {
            component: String::from("API"),
            critical: 1,
            high: 1,
            medium: 1,
            low: 1,
            total: 4,
        }],
        top_findings: vec![TopFinding {
            id: String::from("S-1"),
        }],
        findings_ids: BTreeSet::from([String::from("S-1")]),
    };

    let errors = validate_infographic(&data);

    assert!(errors.is_empty());
}

#[test]
fn validate_infographic_reports_all_consistency_errors() {
    let data = InfographicValidationData {
        metadata: InfographicMetadata {
            total_findings: 6,
            note_count: 1,
            ..Default::default()
        },
        severity_distribution: vec![
            SeverityDistributionEntry {
                label: String::from("Critical"),
                count: 1,
            },
            SeverityDistributionEntry {
                label: String::from("High"),
                count: 1,
            },
        ],
        heat_map: vec![HeatMapRow {
            component: String::from("API"),
            critical: 1,
            high: 1,
            medium: 0,
            low: 1,
            total: 4,
        }],
        top_findings: vec![TopFinding {
            id: String::from("S-9"),
        }],
        findings_ids: BTreeSet::from([String::from("S-1")]),
    };

    let errors = validate_infographic(&data);

    assert_eq!(errors.len(), 3);
    assert!(errors
        .iter()
        .any(|error| error.contains("Severity sum mismatch")));
    assert!(errors
        .iter()
        .any(|error| error.contains("Top finding ID S-9 not found")));
    assert!(errors
        .iter()
        .any(|error| error.contains("Heat map row 'API'")));
}

#[test]
fn compute_component_risk_weights_sorts_by_score_then_component_name() {
    let heat_map = vec![
        HeatMapRow {
            component: String::from("Zulu"),
            critical: 1,
            high: 1,
            medium: 0,
            low: 0,
            total: 2,
        },
        HeatMapRow {
            component: String::from("Alpha"),
            critical: 0,
            high: 2,
            medium: 0,
            low: 0,
            total: 2,
        },
        HeatMapRow {
            component: String::from("Bravo"),
            critical: 0,
            high: 0,
            medium: 0,
            low: 0,
            total: 0,
        },
    ];

    let weights = tachi_core::infographic::compute_component_risk_weights(&heat_map);

    assert_eq!(weights.len(), 3);
    assert_eq!(
        weights[0],
        ComponentRiskWeight {
            component: String::from("Zulu"),
            weight: String::from("high"),
            score: 3.5,
            annotation: String::from("1 Critical + 1 High findings"),
        }
    );
    assert_eq!(
        weights[1],
        ComponentRiskWeight {
            component: String::from("Alpha"),
            weight: String::from("high"),
            score: 3.0,
            annotation: String::from("2 High findings"),
        }
    );
    assert_eq!(
        weights[2],
        ComponentRiskWeight {
            component: String::from("Bravo"),
            weight: String::from("low"),
            score: 0.0,
            annotation: String::from("No findings"),
        }
    );
}

#[test]
fn compute_most_exposed_layer_prefers_count_then_severity_then_layer_id() {
    let layer_distribution = vec![
        MaestroLayerDistributionEntry {
            layer_id: String::from("L2"),
            layer_name: String::from("Layer 2"),
            finding_count: 5,
            highest_severity: String::from("High"),
        },
        MaestroLayerDistributionEntry {
            layer_id: String::from("L1"),
            layer_name: String::from("Layer 1"),
            finding_count: 5,
            highest_severity: String::from("Critical"),
        },
        MaestroLayerDistributionEntry {
            layer_id: String::from("L3"),
            layer_name: String::from("Layer 3"),
            finding_count: 4,
            highest_severity: String::from("Critical"),
        },
    ];

    assert_eq!(
        compute_most_exposed_layer(&layer_distribution),
        "L1 — Layer 1"
    );
}

#[test]
fn compute_most_exposed_layer_returns_empty_when_no_data_exists() {
    assert_eq!(compute_most_exposed_layer(&[]), "");
}
