"""Contract tests for the F-373 K13-posture stale-data gate (T025).

``templates/tachi/security-report/main.typ`` panics with a specific message
when ``report-data.typ`` lacks the ``risk-posture-level``/``risk-posture-label``
variables (D-3 / F-373 K13-posture; see
``.claude/skills/tachi-report-assembly/references/typst-template-contract.md``
"Required, no default"). This module proves both directions on a freshly
generated ``report-data.typ``:

- the positive control: a ``report-data.typ`` generated by the current
  ``extract-report-data.py`` compiles cleanly, with no panic text, and the
  cover renders the fixture's expected risk-posture label;
- the stale case: the same file with the two ``#let risk-posture-*`` lines
  removed fails compilation with the contract's exact panic message.

Fixture: ``tests/scripts/fixtures/fidelity_373/posture_mmdc_free/`` — a
3-finding Tier-1 run with no ``attack-chains.md``, no ``attack-trees/``
directory, and no Mermaid in any Mitigation cell, so
``extract-report-data.py`` never shells out to ``mmdc`` (see the fixture's
own README.md). Residual severities are 1 High / 1 Medium / 1 Low, so the
expected posture is level ``"high"``, label ``"HIGH RISK"``
(``compute_risk_posture``: highest non-zero severity band).

Unlike ``test_coverage_attestation.py``'s T010 stale-data harness, this
module never mutates the real ``templates/tachi/security-report/`` in
place — every compile runs against a ``tmp_path`` COPY of the whole
template directory (tasks.md T025), so a mid-test crash can never corrupt
the working tree.

Typst gating: skipped when ``typst`` is not on PATH, UNLESS
``TACHI_REQUIRE_TYPST=1`` is set (the ``report-posture`` CI job), in which
case a missing Typst FAILS rather than skips (quickstart.md §2).
"""

import os
import shutil
import subprocess
import sys
from pathlib import Path

import pytest


REPO_ROOT = Path(__file__).resolve().parents[2]
SCRIPT_PATH = REPO_ROOT / "scripts" / "extract-report-data.py"
TEMPLATE_DIR = REPO_ROOT / "templates" / "tachi" / "security-report"
FIXTURE_DIR = (
    REPO_ROOT / "tests" / "scripts" / "fixtures" / "fidelity_373" / "posture_mmdc_free"
)

# The contract's exact panic text (typst-template-contract.md "Required, no
# default"). Hardcoded rather than read back out of main.typ: the whole
# point of a contract test is that a silent wording drift in main.typ fails
# it, instead of the test quietly re-deriving whatever text happens to be
# there.
PANIC_TEXT = (
    "report-data.typ predates the risk-posture variables. Regenerate it: "
    "re-run scripts/extract-report-data.py (or /tachi.security-report)."
)

# The fixture's hand-computed expected posture (fixture README.md /
# compensating-controls.md Summary Statistics: 0 Critical, 1 High,
# 1 Medium, 1 Low -> highest non-zero band is High).
EXPECTED_LEVEL = "high"
EXPECTED_LABEL = "HIGH RISK"

SOURCE_DATE_EPOCH = "1700000000"


def _require_typst() -> None:
    """Skip, unless TACHI_REQUIRE_TYPST=1 demands a hard failure instead.

    The report-posture CI job sets TACHI_REQUIRE_TYPST=1 (quickstart.md §2)
    specifically so a broken Typst provisioning step cannot silently
    downgrade this gate to a no-op. Every other environment treats a
    missing ``typst`` as an ordinary skip, matching the rest of the
    suite's presence-guard idiom (e.g. test_coverage_attestation.py's T010
    test).
    """
    if shutil.which("typst"):
        return
    if os.environ.get("TACHI_REQUIRE_TYPST") == "1":
        pytest.fail(
            "TACHI_REQUIRE_TYPST=1 but `typst` is not on PATH. The "
            "report-posture CI job must fail loudly, not skip, when its "
            "own Typst provisioning step is broken."
        )
    pytest.skip("typst CLI not available in test environment")


@pytest.fixture
def template_copy(tmp_path: Path) -> Path:
    """A ``tmp_path`` copy of ``templates/tachi/security-report/``.

    Every compile in this module runs against this copy, never the real
    template directory — T025 forbids the in-tree swap-and-restore pattern
    that ``test_coverage_attestation.py``'s T010 harness uses.
    """
    dest = tmp_path / "security-report"
    shutil.copytree(TEMPLATE_DIR, dest)
    return dest


def _generate_report_data(
    output_path: Path, template_dir: Path, cwd: Path
) -> subprocess.CompletedProcess:
    """Run extract-report-data.py against the mmdc-free posture fixture.

    ``cwd`` MUST be a directory with no ``brand/final`` sibling (never
    REPO_ROOT). ``extract-report-data.py``'s ``detect_brand_assets()``
    checks a bare relative ``Path("brand/final")`` against the process
    cwd, so pointing cwd at the real repo root here would emit a logo path
    computed relative to a *different* template-dir depth than where
    ``template_dir`` (the tmp_path copy) actually lives — a long ``../``
    chain that walks back out to the real ``brand/`` directory. Typst's
    ``--root`` sandboxing then rejects that path once it escapes the
    copy's root: the exact failure stage 3 hit with an external scratch
    copy. Running with a brand-less cwd instead makes
    ``has-logo-primary``/``has-logo-horizontal`` come out False, which is
    fine — this contract has nothing to do with logos.
    """
    cmd = [
        sys.executable,
        str(SCRIPT_PATH),
        "--target-dir",
        str(FIXTURE_DIR),
        "--output",
        str(output_path),
        "--template-dir",
        str(template_dir),
    ]
    return subprocess.run(cmd, cwd=cwd, capture_output=True, text=True)


def _compile(template_dir: Path, pdf_out: Path) -> subprocess.CompletedProcess:
    env = {**os.environ, "SOURCE_DATE_EPOCH": SOURCE_DATE_EPOCH}
    cmd = [
        "typst",
        "compile",
        str(template_dir / "main.typ"),
        str(pdf_out),
        "--root",
        str(template_dir),
    ]
    return subprocess.run(
        cmd, cwd=template_dir, env=env, capture_output=True, text=True
    )


def _strip_posture_lines(report_data_path: Path) -> None:
    """Remove the two risk-posture ``#let`` lines, simulating a pre-K13-posture file.

    Mirrors ``test_coverage_attestation.py``'s own stale-data stripping
    idiom (match on ``.strip().startswith(...)``) rather than a regex, so
    a reformat of the emitted line can't silently defeat the strip.
    """
    content = report_data_path.read_text()
    kept = [
        line
        for line in content.splitlines()
        if not line.strip().startswith("#let risk-posture-level")
        and not line.strip().startswith("#let risk-posture-label")
    ]
    report_data_path.write_text("\n".join(kept) + "\n")


def test_fresh_report_data_compiles_with_expected_posture(template_copy, tmp_path):
    """Positive control: a freshly generated report-data.typ has no panic text.

    Compiles cleanly (exit 0) and the cover renders the fixture's expected
    risk-posture label.
    """
    _require_typst()

    report_data = template_copy / "report-data.typ"
    extract_result = _generate_report_data(report_data, template_copy, cwd=tmp_path)
    assert extract_result.returncode == 0, (
        f"extract-report-data.py failed on the posture fixture.\n"
        f"stdout: {extract_result.stdout}\nstderr: {extract_result.stderr}"
    )
    assert report_data.exists(), "extract-report-data.py did not write report-data.typ"

    data_text = report_data.read_text()
    assert f'#let risk-posture-level = "{EXPECTED_LEVEL}"' in data_text, (
        f'Expected risk-posture-level = "{EXPECTED_LEVEL}" from the fixture\'s '
        f"residual severities (1 High / 1 Medium / 1 Low). Got:\n{data_text}"
    )
    assert f'#let risk-posture-label = "{EXPECTED_LABEL}"' in data_text, (
        f'Expected risk-posture-label = "{EXPECTED_LABEL}". Got:\n{data_text}'
    )

    pdf_out = tmp_path / "fresh-output.pdf"
    compile_result = _compile(template_copy, pdf_out)
    assert compile_result.returncode == 0, (
        f"main.typ compile against a fresh report-data.typ failed.\n"
        f"stdout: {compile_result.stdout}\nstderr: {compile_result.stderr}"
    )
    assert PANIC_TEXT not in compile_result.stderr, (
        "The stale-data panic fired against a freshly generated "
        "report-data.typ that DOES carry both risk-posture variables.\n"
        f"stderr: {compile_result.stderr}"
    )
    assert pdf_out.exists() and pdf_out.stat().st_size > 0

    # Optional, only if pdftotext is cheaply available: confirm the cover
    # page actually renders the label text, not just that the data file
    # carries it.
    if shutil.which("pdftotext"):
        text_result = subprocess.run(
            ["pdftotext", "-f", "1", "-l", "1", str(pdf_out), "-"],
            capture_output=True,
            text=True,
        )
        if text_result.returncode == 0:
            assert EXPECTED_LABEL in text_result.stdout, (
                f"Cover page text does not contain {EXPECTED_LABEL!r}:\n"
                f"{text_result.stdout}"
            )


def test_stale_report_data_panics_with_contract_text(template_copy, tmp_path):
    """The stale case: report-data.typ without the posture #let lines panics.

    Simulates a ``report-data.typ`` generated by a pre-K13-posture
    ``extract-report-data.py`` — the two variables are entirely absent, not
    just ``none``, so main.typ's presence guard (not a
    ``.at(..., default:)`` fallback) must fire.
    """
    _require_typst()

    report_data = template_copy / "report-data.typ"
    extract_result = _generate_report_data(report_data, template_copy, cwd=tmp_path)
    assert extract_result.returncode == 0, (
        f"extract-report-data.py failed on the posture fixture.\n"
        f"stdout: {extract_result.stdout}\nstderr: {extract_result.stderr}"
    )

    _strip_posture_lines(report_data)
    stripped_text = report_data.read_text()
    assert "risk-posture-level" not in stripped_text
    assert "risk-posture-label" not in stripped_text

    pdf_out = tmp_path / "stale-output.pdf"
    compile_result = _compile(template_copy, pdf_out)

    assert compile_result.returncode != 0, (
        "main.typ compiled successfully against a stale report-data.typ "
        "that lacks risk-posture-level/risk-posture-label. The D-3 "
        "presence guard must panic instead of silently rendering a blank "
        "or wrong-color posture badge.\n"
        f"stdout: {compile_result.stdout}"
    )
    assert PANIC_TEXT in compile_result.stderr, (
        f"Expected the contract's exact panic text in stderr.\n"
        f"Expected substring: {PANIC_TEXT!r}\n"
        f"Got stderr: {compile_result.stderr}"
    )
